## prepare devlopment tools
install.packages(c("devtools", "roxygen2", "testthat", "knitr"))
install.packages("rstudioapi")
rstudioapi::isAvailable("0.99.149")
## devtools::install_github("hadley/devtools")

library(devtools)

create("E:/github/R/package-dev/hello")
## edit the DECRIPTION file mannually generated by creat()
countries<-c("China","USA","RUSSIA")
use_data(countries, pkg = "hello")
## insert data(or data-file) into the package("hello") lib

###############################################################
# To compile your R code in the R ducumant(script) 
# with specific format,like following:
# 
# ' Hello Country
# 
# #' @param countries string vertices countaining countries.
# #' @examples
# #' hello_country(countries)
# #' @export
# hello_country <- function(countries) {
#   hellos = paste('Hello',countries)
#   for (i in hellos ){
#     print(i)
#   }
# }
##############################################################
document(pkg = "hello")
use_vignette("hello-tutorial", pkg = "hello")
## modified the readme file of this project manually generated by use_vignette()
## build and pack this project as a R package 
build(pkg = "hello")

